#platform :ios, '9.0'

target 'Todoey' do
  use_frameworks!

  # Pods for Todoey
  
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
  pod 'RealmSwift'
  pod 'SwipeCellKit'
end
